version: 2
jobs:
  test:
    working_directory: ~/helloKtor
    docker:
      - image: gradle:4.10-jdk8
    steps:
      - checkout
      - restore_cache:
          key: circleci-hello-ktor-{{ checksum "build.gradle" }}
      - run: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: circleci-hello-ktor-{{ checksum "build.gradle" }}
      - run: ./gradlew build
      - run: ./gradlew test

workflows:
  version: 2
  build:
    jobs:
      - test
